import { BigNumber, Contract } from 'ethers';

export interface ITokenData {
  address: string;
  decimals: number;
  logoURI: string;
  name: string;
  symbol: string;
}

export interface IApp {
  account: string;
  web3: any;
  router: any;
  exchange: any;
  factory: any;
  Pair: any;
  ethBalanceTokenA: string;
  ethBalanceTokenB: string;
  tokenABalance: string;
  tokenBBalance: string;
  loading: boolean;
  loadingRemoveLp: boolean;
  provider: any;
  signer: any;
  exchangeAddress: string;
  swapTokens(tokenAAmount: BigNumber, tokenBAmount: BigNumber): void;
  addLiquidity(tokenAmount: BigNumber, tokenBAmount: BigNumber): void;
  removeLiquidity(liquidityAmount: string): void;
  getTokenAAmount(tokenAmount: BigNumber): void;
  getTokenBAmount(tokenAmount: BigNumber): void;
  getExchangeAddress(token1: any, token2: any): any;
  getExchange(exchange: any): any;
  getLiquidityOwner(token1Data: ITokenData, token2Data: ITokenData): void;
  getPriceImpact(input: number): void;
  fromWei(value: any): string;
  toWei(value: any): BigNumber;
  isOpenModalSlippage: boolean;
  isOpen: boolean;
  toggleSlippageModal(): void;
  toggleTokenListModal(tokenBSelected: boolean): void;
  setMsg(value: string): any;
  tokensData: ITokenData[];
  tokensGData: ITokenData[];
  tokenAData: ITokenData;
  tokenBData: ITokenData;
  tx: any;
  msg: boolean;
  msgTxt: string;
  outputAddress: any;
  liquidity: any;
  lpPairBalanceAccount: string;
  lpShareAccountviaInput: string;
  lpAccountShare: number;
  priceImpact: number;
  tokenAShare: number;
  tokenBShare: number;
  tokenASelectedShare: string;
  tokenBSelectedShare: string;
  tokenBSelected: boolean;
  outputAmount: any;
  outputAmountInWei: any;
  inputAmount: any;
  inputAmountInWei: any;
  slippage: any;
  setSlippage(slippage: string): any;
  clearStates(): void;
  networkName: string;
  correctNetwork: boolean;
}
